# -*- coding: utf-8 -*-
"""PA - Trabajo 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1NWgid_qKVMe_iBGuncUA6PFqlwYvGj

# Trabajo 02

## Cargar Modulos y Librerias
"""

from modulo import plot_geometry
from Punto2D import Punto2D

"""## Definir los puntos de la estrella"""

A = Punto2D(0, 1)
B = Punto2D(0.95, 0.31)
C = Punto2D(0.59, -0.81)
D = Punto2D(-0.59, -0.81)
E = Punto2D(-0.95, 0.31)

"""## Dibujar la estrella roja"""

plot_geometry(A, B, C, D, E, color='red')

"""## Dibujar estrella amrailla (por defecto)"""

plot_geometry(A, B, C, D, E)

"""## Dibujar estrella cyan

La función plot_geometry no tiene una conversion del color cyan a español, por lo que lo define como un color _**bonito**_.
"""

plot_geometry(A, B, C, D, E, color="cyan")