# -*- coding: utf-8 -*-
"""Semana8parte1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PVyTrJ4vCWbjR6Fsdc_aWBGGEbUHH5Wi

Crar un archivo.cpp y luego leerlo en python
"""

!pip install pybind11

import pybind11
print(pybind11.get_cmake_dir())

#!mkdir build # crear una carpeta llamada build
#% cd build # ir a la carpeta build
#!cmake .. # ejecutar el comando cmake
#!make # ejecutar el comando make

# Commented out IPython magic to ensure Python compatibility.
# %cd build

!cmake ..

!make

!ls

import sys
sys.path.append('/content/build')

import stl_bindings

# Crear dos vectores para sumarlos

a = [1,2,3]
b = [2,3,4]

resultado = stl_bindings.sum_vectors(a,b)
print("la suma de los vectores es ", resultado)

r = stl_bindings.create_map()

type(r)

stl_bindings.saludo()

# Commented out IPython magic to ensure Python compatibility.
# %cd ..

!rm -rf build

# Commented out IPython magic to ensure Python compatibility.
!mkdir -p build
# %cd build

!cmake ..

!make

import sys
sys.path.append('/content/build')

import stl_bindings

# Crear dos vectores para sumarlos

a = [1,2,3]
b = [2,3,4]

resultado = stl_bindings.sum_vectors(a,b)
print("la suma de los vectores es ", resultado)

r = stl_bindings.create_map()

type(r)

!cmake ..

!make

import sys
sys.path.append('/content/build')

import stl_bindings

# Crear dos vectores para sumarlos

a = [1,2,3]
b = [2,3,4]

resultado = stl_bindings.sum_vectors(a,b)
print("la suma de los vectores es ", resultado)

a = stl_bindings.saludo()
print(a)

