# -*- coding: utf-8 -*-
"""Semana8parte2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfLpcsvzK5pAOe3ZbigAWq4yTJFYQkcA

Llamar un archivo Python desde la consola o terminal a través de un archivo bash.
"""

!/content/ejecuta_suma.sh 2 3

!chmod +x ejecuta_suma.sh

!/content/ejecuta_suma.sh 2 3

ls

!/content/ejecuta_suma.sh

import suma

!python3 suma.py 2 3

!/content/ejecuta_suma.sh 2 3

!/content/ejecuta_suma.sh 2 3 4 5 6 7

!/content/ejecuta_suma.sh 2 3 4 5 6 7

